### ISSUE TITLE
The replace array

### ISSUE THREAD

**Issue by ghost** [jdevalk/XML-Sitemap-PHP-Script#4]
Hi there, great script, works very well, apart from the replace file array. It doesn't seem to do the file replacement. I have tested with PHP 5.2 and 5.4.

I have this present in the config file...

$replace = array( 'index.php' => '' );

And this in the script...

```
        if ( in_array( $file, $replace ) )
            $file = $replace[$file];
```

But it doesn't replace http://www.mysite.com/index.php with http://www.mysite.com/

Any help would be appreciated.

**Comment by Treader** [comment]
I know this is WAY late, but I made a pull request #7  to fix this in master. For any others that run into this before the merge: replace the in_array section with isset($replace[$file]) and that should work for you!

**Comment by jdevalk** [comment]
Thanks @Treader for the help here, fixed.
