### ISSUE TITLE
Dates set to 1969 on recursive directories

### ISSUE THREAD

**Issue by fishonstilts** [jdevalk/XML-Sitemap-PHP-Script#5]
This script is setting the dates to "1969-12-31 16:00" on all directories on my site. Am I doing something incorrectly or is this the script? 

My configuration is as follows:

define( 'SITEMAP_DIR', './' );

// With trailing slash!
define( 'SITEMAP_DIR_URL', 'http://www.michaans.com/' );

// Whether or not the script should check recursively.
define( 'RECURSIVE', true );

// The file types, you can just add them on, so 'pdf', 'php' would work
$filetypes = array( 'php', 'html', 'pdf' );

// The replace array, this works as file => replacement, so 'index.php' => '', would make the index.php be listed as just /
$replace = array( 'index.php' => '' );

// The XSL file used for styling the sitemap output, make sure this path is relative to the root of the site.
$xsl = 'xml-sitemap.xsl';

// The Change Frequency for files, should probably not be 'never', unless you know for sure you'll never change them again.
$chfreq = 'never';

// The Priority Frequency for files. There's no way to differentiate so it might just as well be 1.
$prio = 1;

// Ignore array, all files in this array will be: ignored!
$ignore = array( 'config.php' );

**Comment by jollyjollyjolly** [comment]
Check your PHP.ini settings. You have an issue with that.

**Comment by 55sketch** [comment]
I found that changing line 47 from

`$mod = date( 'c', filemtime( $dir . $file ) );`

to 

`$mod = date( 'c', filemtime( $dir . '/' . $file ) );`

Fixed this, at least for one level deep pages.

**Comment by Treader** [comment]
This is late, but future users hopefully will get my merge #7  in master. If not, this should work. look for the recursion section and modify to be:
`parse_dir( $dir . $file . '/', $url . $file . '/' );`

**Comment by jdevalk** [comment]
Fixed in the updates I did today.
