### ISSUE TITLE
Subdirectories not shown with recursion

### ISSUE THREAD

**Issue by compujo** [jdevalk/XML-Sitemap-PHP-Script#6]
I enabled recursion, but the sub directories weren't being shown

This patch seems to work (line 34 in xml-sitemap.php)

```
        if ( is_dir( $dir.$file ) ) {
            if ( defined( 'RECURSIVE' ) && RECURSIVE ) {
                parse_dir( $dir.$file.'/', $url . $file . '/' );
            }
        }
```

**Comment by Treader** [comment]
I found the same issue and issued pull request #7  to get this fixed in master for future users!

**Comment by jdevalk** [comment]
Fixed in the newest version!
